// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIUiXw6vfsm0tv_CwOokZZmeKDSqsf3A',
    appId: '1:252851325812:android:77757e86eaf31880dc3a21',
    messagingSenderId: '252851325812',
    projectId: 'karmaaimobileapp',
    storageBucket: 'karmaaimobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ6trYdgACpZejE-XMGCzegctSfKrYrUY',
    appId: '1:252851325812:ios:797581e26e2e5780dc3a21',
    messagingSenderId: '252851325812',
    projectId: 'karmaaimobileapp',
    storageBucket: 'karmaaimobileapp.firebasestorage.app',
    iosBundleId: 'com.acme.cookingrecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ6trYdgACpZejE-XMGCzegctSfKrYrUY',
    appId: '1:252851325812:ios:572dda261f68c929dc3a21',
    messagingSenderId: '252851325812',
    projectId: 'karmaaimobileapp',
    storageBucket: 'karmaaimobileapp.firebasestorage.app',
    iosBundleId: 'dev.flutter.layers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkP4GdMlPL5EN2oS9pBRRxDYwDgtceEAA',
    appId: '1:252851325812:web:86a60249f9d8fdd0dc3a21',
    messagingSenderId: '252851325812',
    projectId: 'karmaaimobileapp',
    authDomain: 'karmaaimobileapp.firebaseapp.com',
    storageBucket: 'karmaaimobileapp.firebasestorage.app',
    measurementId: 'G-0JKLDLX784',
  );
}
